# Generated by Django 4.2.5 on 2023-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging_App', '0003_rename_name_blog_user_remove_blog_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(default='2023-10-04 10:14'),
        ),
    ]
